---
- name: Decommission Nodes
  hosts: scylla_scale
  become: yes  # This playbook needs to run with sudo to manage system services
  gather_facts: no
  tasks:
    - name: Wait for Scylla server to decommission safely
      ansible.builtin.shell: |
        nodetool decommission
      async: 3600
      poll: 5
      ignore_errors: true

    - name: Stop the Scylla service
      ansible.builtin.systemd:
        name: scylla-server
        state: stopped
      ignore_errors: true

    - name: Remove all files in saved_caches/
      ansible.builtin.shell: "rm -rf /var/lib/scylla/saved_caches/*"
      ignore_errors: true

    - name: Remove all files in coredump/
      ansible.builtin.shell: "rm -rf /var/lib/scylla/coredump/*"
      ignore_errors: true

    - name: Remove all files in logs/
      ansible.builtin.shell: "rm -rf /var/lib/scylla/logs/*"
      ignore_errors: true

    - name: Remove all files in hints/
      ansible.builtin.shell: "rm -rf /var/lib/scylla/hints/*"
      ignore_errors: true

    - name: Remove all files in view_hints/
      ansible.builtin.shell: "rm -rf /var/lib/scylla/view_hints/*"
      ignore_errors: true

    - name: Remove all files in data/
      ansible.builtin.shell: "rm -rf /var/lib/scylla/data/*"
      ignore_errors: true

    - name: Remove all files in commitlog/
      ansible.builtin.shell: "rm -rf /var/lib/scylla/commitlog/*"
      ignore_errors: true