- name: Tune the OS for all nodes
  hosts: all
  become: yes
  vars:
    update_sysctl: True
    sysctl_params:
      - { name: 'fs.file-max', value: '2097152' }
      - { name: 'vm.swappiness', value: '0' }
      - { name: 'vm.dirty_ratio', value: '60' }
      - { name: 'vm.dirty_background_ratio', value: '2' }
      - { name: 'vm.max_map_count', value: '120000' }  # Added for JVM tuning
      - { name: 'net.ipv4.tcp_synack_retries', value: '2' }
      - { name: 'net.ipv4.ip_local_port_range', value: '2000 65535' }
      - { name: 'net.ipv4.tcp_rfc1337', value: '1' }
      - { name: 'net.ipv4.tcp_fin_timeout', value: '15' }
      - { name: 'net.ipv4.tcp_keepalive_time', value: '300' }
      - { name: 'net.ipv4.tcp_keepalive_probes', value: '5' }
      - { name: 'net.ipv4.tcp_keepalive_intvl', value: '15' }
      - { name: 'net.core.rmem_default', value: '31457280' }
      - { name: 'net.core.rmem_max', value: '12582912' }
      - { name: 'net.core.wmem_default', value: '31457280' }
      - { name: 'net.core.wmem_max', value: '12582912' }
      - { name: 'net.core.somaxconn', value: '65535' }
      - { name: 'net.core.netdev_max_backlog', value: '65535' }
      - { name: 'net.core.optmem_max', value: '25165824' }
      - { name: 'net.ipv4.tcp_mem', value: '65535 131072 262144' }
      - { name: 'net.ipv4.udp_mem', value: '65535 131072 262144' }
      - { name: 'net.ipv4.tcp_rmem', value: '8192 87380 16777216' }
      - { name: 'net.ipv4.udp_rmem_min', value: '16384' }
      - { name: 'net.ipv4.tcp_wmem', value: '8192 65535 16777216' }
      - { name: 'net.ipv4.udp_wmem_min', value: '16384' }
      - { name: 'net.ipv4.tcp_max_tw_buckets', value: '1440000' }
      - { name: 'net.ipv4.tcp_tw_reuse', value: '1' }
  tasks:
    - name: Apply sysctl settings dynamically and persistently
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes  # Ensures changes are applied immediately
      loop: "{{ sysctl_params }}"
      
    - name: Add ulimit settings for ubuntu user
      lineinfile:
        path: /etc/security/limits.conf
        line: "{{ item }}"
        create: yes
      with_items:
        - "ubuntu hard nofile 1048576"
        - "ubuntu soft nofile 1048576"
        - "ubuntu hard nproc 65535"
        - "ubuntu soft nproc 65535"
        - "ubuntu hard memlock unlimited"
        - "ubuntu soft memlock unlimited"

    - name: Ensure PAM limits module is enabled
      lineinfile:
        path: /etc/pam.d/common-session
        line: "session required pam_limits.so"
        create: yes
        state: present

    - name: Ensure PAM limits module is enabled for non-interactive sessions
      lineinfile:
        path: /etc/pam.d/common-session-noninteractive
        line: "session required pam_limits.so"
        create: yes
        state: present

    - name: Reload PAM configuration
      debug:
        msg: "PAM configuration updated. Changes will apply on the next session login."

    - name: Ensure snapd is installed
      package:
        name: snapd
        state: present

    - name: Install btop
      community.general.snap:
        name: btop
        state: present
