---
# Use limits (-l) to limit the nodes where the compactions will be run
# To run on multiple nodes at a time, run with `-e "node_batch_size=N"`
# (to run on all nodes use node_batch_size=100%)
#
# Check the vars below for the format of the compaction targets

- name: Run major compaction
  hosts: scylla
  gather_facts: false
  serial: "{{ node_batch_size|default(1) }}"
  vars:
    # compact all tables in keyspace "ks1"
    # compact:
    #   keyspace: ks1

    # compact tables "tb3" and "tb1" in keyspace "ks2"
    # compact:
    #   keyspace: ks2
    #   tables:
    #     - tb3
    #     - tb1

    # compact all the keyspaces and tables on configured nodes
    # compact: all

  tasks:
    - name: Run compaction for all ks/tables
      script:  files/compact.sh -a
      when:
        - compact is defined
        - compact == "all"

    - name: Run ks all tables compactions
      script: files/compact.sh -k "{{ compact['keyspace'] }}"
      when:
        - compact is defined
        - compact.tables is not defined
        - compact.keyspace is defined

    - name: Run ks/tables compaction
      script: files/compact.sh -t {{ compact['keyspace'] }}.{{ item }}
      loop: "{{ compact['tables'] }}"
      when:
        - compact is defined
        - compact.tables is defined
        - compact.keyspace is defined
        - compact != "all"






